### ISSUE TITLE
Docs specify dash vs underscore in require statement?

### ISSUE THREAD

**Issue by davetroy** [railsblueprint/mina-puma-systemd#1]
It looks like there may be a problem in your documentation. Your example says to add `require 'mina/puma-systemd'` to the `deploy.rb` file, but it looks like the current version requires using an underscore rather than a dash (i.e. `require 'mina/puma_systemd').

Is this true or do I have my wires crossed? Thanks for this.

**Comment by elik-ru** [comment]
Hi @davetroy. Thanks for reaching me out. You're right, there is a typo. I just have updated readme file.

**Comment by davetroy** [comment]
Thanks! Glad to know I wasn't hallucinating. :)
